### ISSUE TITLE
似乎没有 kubernetes 镜像的 dockerfile

### ISSUE THREAD

**Issue by liangyuanpeng** [Loongson-Cloud-Community/dockerfiles#247]
容器镜像仓库存在 kubernetes 的镜像 https://cr.loongnix.cn/organization/kubernetes ,但是这个仓库没有看到对应的dockerfiles

**Comment by zhangguanzhang** [comment]
https://github.com/zhangguanzhang/compile-and-packages/tree/master/loong64
可以去参考下，那个patch

**Comment by liangyuanpeng** [comment]
👍  也在网站看到了 https://loongson-cloud-community.github.io/Loongson-Cloud-Community/%E7%A7%BB%E6%A4%8D%E6%89%8B%E5%86%8C/kubernetes/#_3 

如果贴上你这个示例估计会更好
