### ISSUE TITLE
gitlab-runner 的 docker file 记录的链接 404 了

### ISSUE THREAD

**Issue by lindexi** [Loongson-Cloud-Community/dockerfiles#265]
https://github.com/Loongson-Cloud-Community/dockerfiles/blob/2e4969e548cb9c94e06b2b70b2431395001c60ab/gitlab/gitlab-runner/13.11-alpine/install-gitlab-runner#L5

> https://github.com/Loongson-Cloud-Community/gitlab-runner/releases/download/v13.11.0/gitlab-runner-linux-loong64

以上链接已经 404 了

**Comment by yzewei** [comment]
https://cloud.loongnix.cn/releases/loongarch64/gitlab-org/ 去这里拿

**Comment by lindexi** [comment]
@yzewei 多谢大佬
